Update runUnitTestsAndDeploy.yml

diff --git a/.github/workflows/runUnitTestsAndDeploy.yml b/.github/workflows/runUnitTestsAndDeploy.yml
--- a/.github/workflows/runUnitTestsAndDeploy.yml
+++ b/.github/workflows/runUnitTestsAndDeploy.yml
@@ -27,88 +27,88 @@ jobs:
           aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
           aws-region: ${{ vars.AWS_REGION || 'us-east-2' }}
         
-      - name: Run Unit Tests via SSM
-        run: |
-          BRANCH_NAME=$(echo ${GITHUB_REF##*/})
-          echo "Running Unit Tests on branch: $BRANCH_NAME"
+  #     - name: Run Unit Tests via SSM
+  #       run: |
+  #         BRANCH_NAME=$(echo ${GITHUB_REF##*/})
+  #         echo "Running Unit Tests on branch: $BRANCH_NAME"
 
-          COMMAND_ID=$(aws ssm send-command \
-            --document-name "AWS-RunShellScript" \
-            --targets "[{\"Key\":\"tag:Name\",\"Values\":[\"${{ vars.BUILD_SERVER_EC2_INSTANCE_TAG }}\"]}]" \
-            --parameters "commands=['php ${{ vars.UNIT_TESTS_PATH }} $BRANCH_NAME']" \
-            --region ${{ vars.AWS_REGION }} \
-            --query "Command.CommandId" --output text)
+  #         COMMAND_ID=$(aws ssm send-command \
+  #           --document-name "AWS-RunShellScript" \
+  #           --targets "[{\"Key\":\"tag:Name\",\"Values\":[\"${{ vars.BUILD_SERVER_EC2_INSTANCE_TAG }}\"]}]" \
+  #           --parameters "commands=['php ${{ vars.UNIT_TESTS_PATH }} $BRANCH_NAME']" \
+  #           --region ${{ vars.AWS_REGION }} \
+  #           --query "Command.CommandId" --output text)
 
-          echo "Waiting for test execution to complete..."
+  #         echo "Waiting for test execution to complete..."
 
-          while true; do
-            STATUS=$(aws ssm list-command-invocations \
-              --command-id "$COMMAND_ID" \
-              --details \
-              --query "CommandInvocations[0].Status" \
-              --output text \
-              --region ${{ vars.AWS_REGION }})
+  #         while true; do
+  #           STATUS=$(aws ssm list-command-invocations \
+  #             --command-id "$COMMAND_ID" \
+  #             --details \
+  #             --query "CommandInvocations[0].Status" \
+  #             --output text \
+  #             --region ${{ vars.AWS_REGION }})
 
-            echo "Current Status: $STATUS"
+  #           echo "Current Status: $STATUS"
 
-            if [[ "$STATUS" == "Success" ]]; then
-              echo "Unit Tests Passed ✅"
-              break
-            elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
-              echo "Unit Tests Failed ❌"
-              exit 1
-            fi
+  #           if [[ "$STATUS" == "Success" ]]; then
+  #             echo "Unit Tests Passed ✅"
+  #             break
+  #           elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
+  #             echo "Unit Tests Failed ❌"
+  #             exit 1
+  #           fi
             
-            sleep 5
-          done
+  #           sleep 5
+  #         done
 
-  build_upload_s3:
-    runs-on: ubuntu-latest
-    environment: dev
-    needs: unit_tests  # Ensures this runs only after unit tests pass
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4 
+  # build_upload_s3:
+  #   runs-on: ubuntu-latest
+  #   environment: dev
+  #   needs: unit_tests  # Ensures this runs only after unit tests pass
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4 
 
-      - name: Create Build and Upload to S3 via SSM
-        run: |
-          BRANCH_NAME=$(echo ${GITHUB_REF##*/})
-          echo "Creating Build and uploading artifact to S3: $BRANCH_NAME"
+  #     - name: Create Build and Upload to S3 via SSM
+  #       run: |
+  #         BRANCH_NAME=$(echo ${GITHUB_REF##*/})
+  #         echo "Creating Build and uploading artifact to S3: $BRANCH_NAME"
 
-          COMMAND_ID=$(aws ssm send-command \
-            --document-name "AWS-RunShellScript" \
-            --targets "[{\"Key\":\"tag:Name\",\"Values\":[\"${{ secrets.EC2_INSTANCE_TAG }}\"]}]" \
-            --parameters "commands=['cd /home/ec2-user/deployer && dep deploy --branch=${BRANCH_NAME}', 'cd ${{ vars.BRANCH_PATH }}${BRANCH_NAME} && tar --zstd -cf ${{vars.BRANCH_ARCHIVES_PATH}}${BRANCH_NAME}.tar.zst ./.', 'aws s3 cp ${{vars.BRANCH_ARCHIVES_PATH}}${BRANCH_NAME}.tar.zst ${{ vars.S3_BUILD_PATH }}']" \
-            --region ${{ vars.AWS_REGION }} \
-            --query "Command.CommandId" --output text)
+  #         COMMAND_ID=$(aws ssm send-command \
+  #           --document-name "AWS-RunShellScript" \
+  #           --targets "[{\"Key\":\"tag:Name\",\"Values\":[\"${{ secrets.EC2_INSTANCE_TAG }}\"]}]" \
+  #           --parameters "commands=['cd /home/ec2-user/deployer && dep deploy --branch=${BRANCH_NAME}', 'cd ${{ vars.BRANCH_PATH }}${BRANCH_NAME} && tar --zstd -cf ${{vars.BRANCH_ARCHIVES_PATH}}${BRANCH_NAME}.tar.zst ./.', 'aws s3 cp ${{vars.BRANCH_ARCHIVES_PATH}}${BRANCH_NAME}.tar.zst ${{ vars.S3_BUILD_PATH }}']" \
+  #           --region ${{ vars.AWS_REGION }} \
+  #           --query "Command.CommandId" --output text)
 
-          echo "Waiting for build and upload to complete..."
+  #         echo "Waiting for build and upload to complete..."
 
-          while true; do
-            STATUS=$(aws ssm list-command-invocations \
-              --command-id "$COMMAND_ID" \
-              --details \
-              --query "CommandInvocations[0].Status" \
-              --output text \
-              --region ${{ vars.AWS_REGION }})
+  #         while true; do
+  #           STATUS=$(aws ssm list-command-invocations \
+  #             --command-id "$COMMAND_ID" \
+  #             --details \
+  #             --query "CommandInvocations[0].Status" \
+  #             --output text \
+  #             --region ${{ vars.AWS_REGION }})
 
-            echo "Current Status: $STATUS"
+  #           echo "Current Status: $STATUS"
 
-            if [[ "$STATUS" == "Success" ]]; then
-              echo "Build & Upload Completed ✅"
-              break
-            elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
-              echo "Build & Upload Failed ❌"
-              exit 1
-            fi
+  #           if [[ "$STATUS" == "Success" ]]; then
+  #             echo "Build & Upload Completed ✅"
+  #             break
+  #           elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
+  #             echo "Build & Upload Failed ❌"
+  #             exit 1
+  #           fi
             
-            sleep 5
-          done
+  #           sleep 5
+  #         done
 
   deploy_asg:
     runs-on: ubuntu-latest
     environment: dev
-    needs: build_upload_s3  # Ensures deployment happens only after build & upload
+    # needs: build_upload_s3  # Ensures deployment happens only after build & upload
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4 
