changes

diff --git a/.github/workflows/runUnitTestsAndDeploy.yml b/.github/workflows/runUnitTestsAndDeploy.yml
--- a/.github/workflows/runUnitTestsAndDeploy.yml
+++ b/.github/workflows/runUnitTestsAndDeploy.yml
@@ -12,7 +12,7 @@ on:
     branches:
       - temp_apcu_poc_aws
   pull_request:
-    types: [closed]
+    types: [ closed ]
     branches:
       - temp_apcu_poc_aws
 
@@ -106,62 +106,62 @@ jobs:
 
           # Debugging step to see the value of INSTANCE_ID
           echo "Retrieved INSTANCE_ID = $INSTANCE_ID"
-            echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
+          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
 
       - name: Create Build and Upload to S3 via SSM
         run: |
           BRANCH_NAME=${GITHUB_REF#refs/heads/}
           BRANCH_NAME_PATH=$(echo ${GITHUB_REF#refs/heads/} | sed 's|/|-|g')
           echo "Creating Build and uploading artifact to S3: $BRANCH_NAME"
-
+          
           COMMAND_ID=$(aws ssm send-command \
-            --document-name "AWS-RunShellScript" \
-            --targets '[{"Key":"InstanceIds","Values":["${{ env.INSTANCE_ID }}"]}]' \
-            --parameters "commands=[
-                'sudo -u ec2-user bash -c \"cd /home/ec2-user/deployer/build_server && source ~/.bashrc && /usr/local/bin/dep deploy --branch=${BRANCH_NAME}\"',
-                'sudo -u ec2-user bash -c \"source ~/.bashrc && cd /web_branch/branches/${BRANCH_NAME_PATH} && tar --zstd -cf /web_branch/archives/${BRANCH_NAME_PATH}.tar.zst ./.\"',
-                'sudo -u ec2-user bash -c \"export PATH=$PATH:/home/ec2-user/.local/bin:/usr/local/bin && aws s3 cp /web_branch/archives/${BRANCH_NAME_PATH}.tar.zst s3://csm-saccess-s3-${{ env.ENVIRONMENT }}-builds-us-east-2-bucket/\"'
-            ]" \
-            --region ${{ vars.AWS_REGION }} \
-            --query "Command.CommandId" --output text)
-
+          --document-name "AWS-RunShellScript" \
+          --targets '[{"Key":"InstanceIds","Values":["${{ env.INSTANCE_ID }}"]}]' \
+          --parameters "commands=[
+             'sudo -u ec2-user bash -c \"cd /home/ec2-user/deployer/build_server && source ~/.bashrc && /usr/local/bin/dep deploy --branch=${BRANCH_NAME}\"',
+             'sudo -u ec2-user bash -c \"source ~/.bashrc && cd /web_branch/branches/${BRANCH_NAME_PATH} && tar --zstd -cf /web_branch/archives/${BRANCH_NAME_PATH}.tar.zst ./.\"',
+             'sudo -u ec2-user bash -c \"export PATH=$PATH:/home/ec2-user/.local/bin:/usr/local/bin && aws s3 cp /web_branch/archives/${BRANCH_NAME_PATH}.tar.zst s3://csm-saccess-s3-${{ env.ENVIRONMENT }}-builds-us-east-2-bucket/\"'
+          ]" \
+          --region ${{ vars.AWS_REGION }} \
+          --query "Command.CommandId" --output text)
+          
           echo "Waiting for build and upload to complete..."
-
+          
           while true; do
-            STATUS=$(aws ssm list-command-invocations \
-              --command-id "$COMMAND_ID" \
-              --details \
-              --query "CommandInvocations[0].Status" \
-              --output text \
-              --region ${{ vars.AWS_REGION }})
-
-            echo "Current Status: $STATUS"
-
-            if [[ "$STATUS" == "Success" ]]; then
-              echo "Build & Upload Completed ✅"
-              break
-            elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
-              echo "Build & Upload Failed ❌"
-              OUTPUT=$(aws ssm get-command-invocation \
-                  --command-id "$COMMAND_ID" \
-                  --instance-id "${{ vars.INSTANCE_ID }}" \
-                  --region ${{ vars.AWS_REGION }} \
-                  --query "StandardOutputContent" --output text)
-    
-              echo "Command Output:"
-              echo "$OUTPUT"
-#              exit 1
-            fi
-            
-            sleep 5
+          STATUS=$(aws ssm list-command-invocations \
+           --command-id "$COMMAND_ID" \
+           --details \
+           --query "CommandInvocations[0].Status" \
+           --output text \
+           --region ${{ vars.AWS_REGION }})
+          
+          echo "Current Status: $STATUS"
+          
+          if [[ "$STATUS" == "Success" ]]; then
+           echo "Build & Upload Completed ✅"
+           break
+          elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
+           echo "Build & Upload Failed ❌"
+           OUTPUT=$(aws ssm get-command-invocation \
+               --command-id "$COMMAND_ID" \
+               --instance-id "${{ vars.INSTANCE_ID }}" \
+               --region ${{ vars.AWS_REGION }} \
+               --query "StandardOutputContent" --output text)
+          
+           echo "Command Output:"
+           echo "$OUTPUT"
+          #              exit 1
+          fi
+          
+          sleep 5
           done
           # Fetch the command output once completed
           OUTPUT=$(aws ssm get-command-invocation \
-              --command-id "$COMMAND_ID" \
-              --instance-id "${{ vars.INSTANCE_ID }}" \
-              --region ${{ vars.AWS_REGION }} \
-              --query "StandardOutputContent" --output text)
-
+          --command-id "$COMMAND_ID" \
+          --instance-id "${{ vars.INSTANCE_ID }}" \
+          --region ${{ vars.AWS_REGION }} \
+          --query "StandardOutputContent" --output text)
+          
           echo "Command Output:"
           echo "$OUTPUT"
 
