added unit tests

diff --git a/.github/workflows/runUnitTestsAndDeploy.yml b/.github/workflows/runUnitTestsAndDeploy.yml
--- a/.github/workflows/runUnitTestsAndDeploy.yml
+++ b/.github/workflows/runUnitTestsAndDeploy.yml
@@ -17,160 +17,183 @@ on:
       - temp_apcu_poc_aws
 
 jobs:
-  #  unit_tests:
-  #    runs-on: ubuntu-latest
-  #    environment: dev
-  #    steps:
-  #      - name: Checkout Repository
-  #        uses: actions/checkout@v4
-  #
-  #      - name: Configure AWS Credentials
-  #        uses: aws-actions/configure-aws-credentials@v2
-  #        with:
-  #          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
-  #          aws-region: ${{ vars.AWS_REGION || 'us-east-2' }}
-  #
-  #      - name: Run Unit Tests via SSM
-  #        run: |
-  #          BRANCH_NAME=$(echo ${GITHUB_REF##*/})
-  #          echo "Running Unit Tests on branch: $BRANCH_NAME"
-  #
-  #          COMMAND_ID=$(aws ssm send-command \
-  #            --document-name "AWS-RunShellScript" \
-  #            --targets '[{"Key":"InstanceIds","Values":["${{ vars.BUILD_SERVER_EC2_INSTANCE_TAG }}"]}]' \
-  #            --parameters "commands=['php /web_branch/branches/unitests/runUnitTests.php $BRANCH_NAME']" \
-  #            --region ${{ vars.AWS_REGION }} \
-  #            --query "Command.CommandId" --output text)
-  #
-  #          echo "Waiting for test execution to complete..."
-  #
-  #          while true; do
-  #            STATUS=$(aws ssm list-command-invocations \
-  #              --command-id "$COMMAND_ID" \
-  #              --details \
-  #              --query "CommandInvocations[0].Status" \
-  #              --output text \
-  #              --region ${{ vars.AWS_REGION }})
-  #
-  #            echo "Current Status: $STATUS"
-  #
-  #            if [[ "$STATUS" == "Success" ]]; then
-  #              echo "Unit Tests Passed ✅"
-  #              break
-  #            elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
-  #              echo "Unit Tests Failed ❌"
-  #              exit 1
-  #            fi
-  #
-  #            sleep 5
-  #          done
-  #          # Fetch the command output once completed
-  #          OUTPUT=$(aws ssm get-command-invocation \
-  #              --command-id "$COMMAND_ID" \
-  #              --instance-id "${{ vars.BUILD_SERVER_EC2_INSTANCE_TAG }}" \
-  #              --region ${{ vars.AWS_REGION }} \
-  #              --query "StandardOutputContent" --output text)
-  #
-  #          echo "Command Output:"
-  #          echo "$OUTPUT"
+    unit_tests:
+      runs-on: ubuntu-latest
+      environment: dev
+      steps:
+        - name: Checkout Repository
+          uses: actions/checkout@v4
+
+        - name: Configure AWS Credentials
+          uses: aws-actions/configure-aws-credentials@v2
+          with:
+            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
+            aws-region: ${{ vars.AWS_REGION || 'us-east-2' }}
+
+        - name: Fetch EC2 Instance ID
+          id: fetch_instance_id
+          run: |
+            # Fetch the running EC2 instance ID based on the tag and instance state being 'running'
+            INSTANCE_ID=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=csm-saccess-${{ env.ENVIRONMENT }}-ec2-build" \
+                        "Name=instance-state-name,Values=running" \
+              --query "Reservations[*].Instances[*].InstanceId" \
+              --output text)
+
+            # Debugging step to see the value of INSTANCE_ID
+            echo "Retrieved INSTANCE_ID = $INSTANCE_ID"
+            echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
+
+        - name: Run Unit Tests via SSM
+          run: |
+            BRANCH_NAME=$(echo ${GITHUB_REF##*/})
+            echo "Running Unit Tests on branch: $BRANCH_NAME"
+
+            COMMAND_ID=$(aws ssm send-command \
+              --document-name "AWS-RunShellScript" \
+              --targets '[{"Key":"InstanceIds","Values":["${{ vars.INSTANCE_ID }}"]}]' \
+              --parameters "commands=['php /home/ec2-user/unit_test/runUnitTests.php $BRANCH_NAME']" \
+              --region ${{ vars.AWS_REGION }} \
+              --query "Command.CommandId" --output text)
+
+            echo "Waiting for test execution to complete..."
+
+            while true; do
+              STATUS=$(aws ssm list-command-invocations \
+                --command-id "$COMMAND_ID" \
+                --details \
+                --query "CommandInvocations[0].Status" \
+                --output text \
+                --region ${{ vars.AWS_REGION }})
+
+              echo "Current Status: $STATUS"
+
+              if [[ "$STATUS" == "Success" ]]; then
+                echo "Unit Tests Passed ✅"
+                break
+              elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
+                echo "Unit Tests Failed ❌"
+                OUTPUT=$(aws ssm get-command-invocation \
+                --command-id "$COMMAND_ID" \
+                --instance-id "${{ vars.INSTANCE_ID }}" \
+                --region ${{ vars.AWS_REGION }} \
+                --query "StandardOutputContent" --output text)
+
+                echo "Command Output:"
+                echo "$OUTPUT"
+                exit 1
+              fi
+
+              sleep 5
+            done
+            # Fetch the command output once completed
+            OUTPUT=$(aws ssm get-command-invocation \
+                --command-id "$COMMAND_ID" \
+                --instance-id "${{ vars.INSTANCE_ID }}" \
+                --region ${{ vars.AWS_REGION }} \
+                --query "StandardOutputContent" --output text)
+
+            echo "Command Output:"
+            echo "$OUTPUT"
 
 
-#  build_upload_s3:
-#    runs-on: ubuntu-latest
-#    environment: ${{ inputs.ENVIRONMENT || 'dev' }}
-#    env:
-#      ENVIRONMENT: ${{ inputs.ENVIRONMENT || 'dev' }}
-#    steps:
-#      - name: Checkout Repository
-#        uses: actions/checkout@v4
-#
-#      - name: Configure AWS Credentials
-#        uses: aws-actions/configure-aws-credentials@v2
-#        with:
-#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-#          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
-#          aws-region: ${{ vars.AWS_REGION || 'us-east-2' }}
-#
-#      - name: Fetch EC2 Instance ID
-#        id: fetch_instance_id
-#        run: |
-#          # Fetch the running EC2 instance ID based on the tag and instance state being 'running'
-#          INSTANCE_ID=$(aws ec2 describe-instances \
-#            --filters "Name=tag:Name,Values=csm-saccess-${{ env.ENVIRONMENT }}-ec2-build" \
-#                      "Name=instance-state-name,Values=running" \
-#            --query "Reservations[*].Instances[*].InstanceId" \
-#            --output text)
-#
-#          # Debugging step to see the value of INSTANCE_ID
-#          echo "Retrieved INSTANCE_ID = $INSTANCE_ID"
-#          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
-#
-#      - name: Create Build and Upload to S3 via SSM
-#        run: |
-#          BRANCH_NAME=${GITHUB_REF#refs/heads/}
-#          BRANCH_NAME_PATH=$(echo ${GITHUB_REF#refs/heads/} | sed 's|/|-|g')
-#          echo "Creating Build and uploading artifact to S3: $BRANCH_NAME"
-#
-#          COMMAND_ID=$(aws ssm send-command \
-#          --document-name "AWS-RunShellScript" \
-#          --targets '[{"Key":"InstanceIds","Values":["${{ env.INSTANCE_ID }}"]}]' \
-#          --parameters "commands=[
-#             'sudo -u ec2-user bash -c \"cd /home/ec2-user/deployer/build_server && source ~/.bashrc && /usr/local/bin/dep deploy --branch=${BRANCH_NAME}\"',
-#             'sudo -u ec2-user bash -c \"source ~/.bashrc && cd /web_branch/branches/${BRANCH_NAME_PATH} && tar --zstd -cf /web_branch/archives/${BRANCH_NAME_PATH}.tar.zst ./.\"',
-#             'sudo -u ec2-user bash -c \"export PATH=$PATH:/home/ec2-user/.local/bin:/usr/local/bin && aws s3 cp /web_branch/archives/${BRANCH_NAME_PATH}.tar.zst s3://csm-saccess-s3-${{ env.ENVIRONMENT }}-builds-us-east-2-bucket/\"'
-#          ]" \
-#          --region ${{ vars.AWS_REGION }} \
-#          --query "Command.CommandId" --output text)
-#
-#          echo "Waiting for build and upload to complete..."
-#
-#          while true; do
-#          STATUS=$(aws ssm list-command-invocations \
-#           --command-id "$COMMAND_ID" \
-#           --details \
-#           --query "CommandInvocations[0].Status" \
-#           --output text \
-#           --region ${{ vars.AWS_REGION }})
-#
-#          echo "Current Status: $STATUS"
-#
-#          if [[ "$STATUS" == "Success" ]]; then
-#           echo "Build & Upload Completed ✅"
-#           break
-#          elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
-#           echo "Build & Upload Failed ❌"
-#           OUTPUT=$(aws ssm get-command-invocation \
-#               --command-id "$COMMAND_ID" \
-#               --instance-id "${{ env.INSTANCE_ID }}" \
-#               --region ${{ vars.AWS_REGION }} \
-#               --query "StandardOutputContent" --output text)
-#
-#           echo "Command Output:"
-#           echo "$OUTPUT"
-#           exit 1
-#          fi
-#
-#          sleep 5
-#          done
-#          # Fetch the command output once completed
-#          OUTPUT=$(aws ssm get-command-invocation \
-#          --command-id "$COMMAND_ID" \
-#          --instance-id "${{ env.INSTANCE_ID }}" \
-#          --region ${{ vars.AWS_REGION }} \
-#          --query "StandardOutputContent" --output text)
-#
-#          echo "Command Output:"
-#          echo "$OUTPUT"
+  build_upload_s3:
+    runs-on: ubuntu-latest
+    environment: ${{ inputs.ENVIRONMENT || 'dev' }}
+    env:
+      ENVIRONMENT: ${{ inputs.ENVIRONMENT || 'dev' }}
+    needs: unit_tests
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
+          aws-region: ${{ vars.AWS_REGION || 'us-east-2' }}
+
+      - name: Fetch EC2 Instance ID
+        id: fetch_instance_id
+        run: |
+          # Fetch the running EC2 instance ID based on the tag and instance state being 'running'
+          INSTANCE_ID=$(aws ec2 describe-instances \
+            --filters "Name=tag:Name,Values=csm-saccess-${{ env.ENVIRONMENT }}-ec2-build" \
+                      "Name=instance-state-name,Values=running" \
+            --query "Reservations[*].Instances[*].InstanceId" \
+            --output text)
+
+          # Debugging step to see the value of INSTANCE_ID
+          echo "Retrieved INSTANCE_ID = $INSTANCE_ID"
+          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
+
+      - name: Create Build and Upload to S3 via SSM
+        run: |
+          BRANCH_NAME=${GITHUB_REF#refs/heads/}
+          BRANCH_NAME_PATH=$(echo ${GITHUB_REF#refs/heads/} | sed 's|/|-|g')
+          echo "Creating Build and uploading artifact to S3: $BRANCH_NAME"
+
+          COMMAND_ID=$(aws ssm send-command \
+          --document-name "AWS-RunShellScript" \
+          --targets '[{"Key":"InstanceIds","Values":["${{ env.INSTANCE_ID }}"]}]' \
+          --parameters "commands=[
+             'sudo -u ec2-user bash -c \"cd /home/ec2-user/deployer/build_server && source ~/.bashrc && /usr/local/bin/dep deploy --branch=${BRANCH_NAME}\"',
+             'sudo -u ec2-user bash -c \"source ~/.bashrc && cd /web_branch/branches/${BRANCH_NAME_PATH} && tar --zstd -cf /web_branch/archives/${BRANCH_NAME_PATH}.tar.zst ./.\"',
+             'sudo -u ec2-user bash -c \"export PATH=$PATH:/home/ec2-user/.local/bin:/usr/local/bin && aws s3 cp /web_branch/archives/${BRANCH_NAME_PATH}.tar.zst s3://csm-saccess-s3-${{ env.ENVIRONMENT }}-builds-us-east-2-bucket/\"'
+          ]" \
+          --region ${{ vars.AWS_REGION }} \
+          --query "Command.CommandId" --output text)
+
+          echo "Waiting for build and upload to complete..."
+
+          while true; do
+          STATUS=$(aws ssm list-command-invocations \
+           --command-id "$COMMAND_ID" \
+           --details \
+           --query "CommandInvocations[0].Status" \
+           --output text \
+           --region ${{ vars.AWS_REGION }})
+
+          echo "Current Status: $STATUS"
+
+          if [[ "$STATUS" == "Success" ]]; then
+           echo "Build & Upload Completed ✅"
+           break
+          elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
+           echo "Build & Upload Failed ❌"
+           OUTPUT=$(aws ssm get-command-invocation \
+               --command-id "$COMMAND_ID" \
+               --instance-id "${{ env.INSTANCE_ID }}" \
+               --region ${{ vars.AWS_REGION }} \
+               --query "StandardOutputContent" --output text)
+
+           echo "Command Output:"
+           echo "$OUTPUT"
+           exit 1
+          fi
+
+          sleep 5
+          done
+          # Fetch the command output once completed
+          OUTPUT=$(aws ssm get-command-invocation \
+          --command-id "$COMMAND_ID" \
+          --instance-id "${{ env.INSTANCE_ID }}" \
+          --region ${{ vars.AWS_REGION }} \
+          --query "StandardOutputContent" --output text)
+
+          echo "Command Output:"
+          echo "$OUTPUT"
 
   deploy_asg:
     runs-on: ubuntu-latest
     environment: ${{ inputs.ENVIRONMENT || 'dev' }}
     env:
       ENVIRONMENT: ${{ inputs.ENVIRONMENT || 'dev' }}
-#    needs: build_upload_s3  # Ensures deployment happens only after build & upload
+    needs: build_upload_s3  # Ensures deployment happens only after build & upload
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
