Test 4

diff --git a/.github/workflows/runUnitTestsAndDeploy.yml b/.github/workflows/runUnitTestsAndDeploy.yml
--- a/.github/workflows/runUnitTestsAndDeploy.yml
+++ b/.github/workflows/runUnitTestsAndDeploy.yml
@@ -103,35 +103,41 @@ jobs:
             --document-name "AWS-RunShellScript" \
             --targets '[{"Key":"InstanceIds","Values":["${{ vars.BUILD_SERVER_EC2_INSTANCE_TAG }}"]}]' \
             --parameters "commands=[
-            'sudo -u ec2-user bash -c \"cd /home/ec2-user/deployer/build_server && source ~/.bashrc && /usr/local/bin/dep deploy --branch=${BRANCH_NAME}\"',
-            'sudo -u ec2-user bash -c \"source ~/.bashrc && cd ${{ vars.BRANCH_PATH }}${BRANCH_NAME} && tar --zstd -cf ${{vars.BRANCH_ARCHIVES_PATH}}${BRANCH_NAME}.tar.zst ./.\"',
-            'sudo -u ec2-user bash -c \"export PATH=$PATH:/home/ec2-user/.local/bin:/usr/local/bin && aws s3 cp ${{vars.BRANCH_ARCHIVES_PATH}}${BRANCH_NAME}.tar.zst ${{ vars.S3_BUILD_PATH }}\"'
-          ]" \
+                'sudo -u ec2-user bash -c \"cd /home/ec2-user/deployer/build_server && source ~/.bashrc && /usr/local/bin/dep deploy --branch=${BRANCH_NAME}\"',
+                'sudo -u ec2-user bash -c \"source ~/.bashrc && cd ${{ vars.BRANCH_PATH }}${BRANCH_NAME} && tar --zstd -cf ${{vars.BRANCH_ARCHIVES_PATH}}${BRANCH_NAME}.tar.zst ./.\"',
+                'sudo -u ec2-user bash -c \"export PATH=$PATH:/home/ec2-user/.local/bin:/usr/local/bin && aws s3 cp ${{vars.BRANCH_ARCHIVES_PATH}}${BRANCH_NAME}.tar.zst ${{ vars.S3_BUILD_PATH }}\"'
+            ]" \
             --region ${{ vars.AWS_REGION }} \
-            --query "Command.CommandId" --output text \
-            --cloud-watch-output-config '{"CloudWatchOutputEnabled":true, "CloudWatchLogGroupName":"/aws/ssm/commands"}')
+            --query "Command.CommandId" --output text)
 
           echo "Waiting for build and upload to complete..."
 
           while true; do
-            STATUS=$(aws ssm list-command-invocations \
-              --command-id "$COMMAND_ID" \
-              --details \
-              --query "CommandInvocations[0].Status" \
-              --output text \
-              --region ${{ vars.AWS_REGION }})
-
-            echo "Current Status: $STATUS"
-
-            if [[ "$STATUS" == "Success" ]]; then
-              echo "Build & Upload Completed ✅"
-              break
-            elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
-              echo "Build & Upload Failed ❌"
-              exit 1
-            fi
-
-            sleep 5
+          STATUS=$(aws ssm list-command-invocations \
+          --command-id "$COMMAND_ID" \
+          --details \
+          --query "CommandInvocations[0].Status" \
+          --output text \
+          --region ${{ vars.AWS_REGION }})
+        
+          echo "Current Status: $STATUS"
+        
+          # Fetch partial output and print it
+          aws ssm get-command-invocation \
+          --command-id "$COMMAND_ID" \
+          --instance-id "${{ vars.BUILD_SERVER_EC2_INSTANCE_TAG }}" \
+          --region ${{ vars.AWS_REGION }} \
+          --query "StandardOutputContent" --output text
+        
+          if [[ "$STATUS" == "Success" ]]; then
+          echo "Build & Upload Completed ✅"
+          break
+          elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
+          echo "Build & Upload Failed ❌"
+          exit 1
+          fi
+        
+          sleep 5
           done
           # Fetch the command output once completed
           OUTPUT=$(aws ssm get-command-invocation \
