Test 1

diff --git a/.github/workflows/runUnitTestsAndDeploy.yml b/.github/workflows/runUnitTestsAndDeploy.yml
--- a/.github/workflows/runUnitTestsAndDeploy.yml
+++ b/.github/workflows/runUnitTestsAndDeploy.yml
@@ -32,45 +32,50 @@ jobs:
           BRANCH_NAME=$(echo ${GITHUB_REF##*/})
           echo "Running Unit Tests on branch: $BRANCH_NAME"
 
-          COMMAND_ID=$(aws ssm send-command \
-            --document-name "AWS-RunShellScript" \
-            --targets '[{"Key":"InstanceIds","Values":["${{ vars.BUILD_SERVER_EC2_INSTANCE_TAG }}"]}]' \
-            --parameters "commands=['php ${{ vars.UNIT_TESTS_PATH }} $BRANCH_NAME']" \
-            --region ${{ vars.AWS_REGION }} \
-            --query "Command.CommandId" --output text)
+          aws ssm start-session \
+                      --target "${{ vars.BUILD_SERVER_EC2_INSTANCE_TAG }}" \
+                      --document-name AWS-StartInteractiveCommand \
+                      --parameters "command=['php ${{ vars.UNIT_TESTS_PATH }} $BRANCH_NAME']" \
+                      --region ${{ vars.AWS_REGION }}
+#          COMMAND_ID=$(aws ssm send-command \
+#            --document-name "AWS-RunShellScript" \
+#            --targets '[{"Key":"InstanceIds","Values":["${{ vars.BUILD_SERVER_EC2_INSTANCE_TAG }}"]}]' \
+#            --parameters "commands=['php ${{ vars.UNIT_TESTS_PATH }} $BRANCH_NAME']" \
+#            --region ${{ vars.AWS_REGION }} \
+#            --query "Command.CommandId" --output text)
+#
+#          echo "Waiting for test execution to complete..."
+#
+#          while true; do
+#            STATUS=$(aws ssm list-command-invocations \
+#              --command-id "$COMMAND_ID" \
+#              --details \
+#              --query "CommandInvocations[0].Status" \
+#              --output text \
+#              --region ${{ vars.AWS_REGION }})
+#
+#            echo "Current Status: $STATUS"
+#
+#            if [[ "$STATUS" == "Success" ]]; then
+#              echo "Unit Tests Passed ✅"
+#              break
+#            elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
+#              echo "Unit Tests Failed ❌"
+#              exit 1
+#            fi
+#
+#            sleep 5
+#          done
+#          # Fetch the command output once completed
+#          OUTPUT=$(aws ssm get-command-invocation \
+#              --command-id "$COMMAND_ID" \
+#              --instance-id "${{ vars.BUILD_SERVER_EC2_INSTANCE_TAG }}" \
+#              --region ${{ vars.AWS_REGION }} \
+#              --query "StandardOutputContent" --output text)
+#
+#          echo "Command Output:"
+#          echo "$OUTPUT"
 
-          echo "Waiting for test execution to complete..."
-
-          while true; do
-            STATUS=$(aws ssm list-command-invocations \
-              --command-id "$COMMAND_ID" \
-              --details \
-              --query "CommandInvocations[0].Status" \
-              --output text \
-              --region ${{ vars.AWS_REGION }})
-
-            echo "Current Status: $STATUS"
-
-            if [[ "$STATUS" == "Success" ]]; then
-              echo "Unit Tests Passed ✅"
-              break
-            elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
-              echo "Unit Tests Failed ❌"
-              exit 1
-            fi
-            
-            sleep 5
-          done
-          # Fetch the command output once completed
-          OUTPUT=$(aws ssm get-command-invocation \
-              --command-id "$COMMAND_ID" \
-              --instance-id "${{ vars.BUILD_SERVER_EC2_INSTANCE_TAG }}" \
-              --region ${{ vars.AWS_REGION }} \
-              --query "StandardOutputContent" --output text)
-          
-          echo "Command Output:"
-          echo "$OUTPUT"
-          
 
   build_upload_s3:
     runs-on: ubuntu-latest
@@ -94,53 +99,48 @@ jobs:
           BRANCH_NAME_PATH=$(echo ${GITHUB_REF##*/} | sed 's|/|-|g')
           echo "Creating Build and uploading artifact to S3: $BRANCH_NAME"
 
-          aws ssm start-session \
-                      --target "${{ vars.BUILD_SERVER_EC2_INSTANCE_TAG }}" \
-                      --document-name AWS-StartInteractiveCommand \
-                      --parameters "command=['php ${{ vars.UNIT_TESTS_PATH }} $BRANCH_NAME']" \
-                      --region ${{ vars.AWS_REGION }}
-#          COMMAND_ID=$(aws ssm send-command \
-#            --document-name "AWS-RunShellScript" \
-#            --targets '[{"Key":"InstanceIds","Values":["${{ vars.BUILD_SERVER_EC2_INSTANCE_TAG }}"]}]' \
-#            --parameters "commands=[
-#                'sudo -u ec2-user bash -c \"cd /home/ec2-user/deployer/build_server && source ~/.bashrc && /usr/local/bin/dep deploy --branch=${BRANCH_NAME}\"',
-#                'sudo -u ec2-user bash -c \"source ~/.bashrc && cd ${{ vars.BRANCH_PATH }}${BRANCH_NAME_PATH} && tar --zstd -cf ${{vars.BRANCH_ARCHIVES_PATH}}${BRANCH_NAME_PATH}.tar.zst ./.\"',
-#                'sudo -u ec2-user bash -c \"export PATH=$PATH:/home/ec2-user/.local/bin:/usr/local/bin && aws s3 cp ${{vars.BRANCH_ARCHIVES_PATH}}${BRANCH_NAME_PATH}.tar.zst ${{ vars.S3_BUILD_PATH }}\"'
-#            ]" \
-#            --region ${{ vars.AWS_REGION }} \
-#            --query "Command.CommandId" --output text)
-#
-#          echo "Waiting for build and upload to complete..."
-#
-#          while true; do
-#            STATUS=$(aws ssm list-command-invocations \
-#              --command-id "$COMMAND_ID" \
-#              --details \
-#              --query "CommandInvocations[0].Status" \
-#              --output text \
-#              --region ${{ vars.AWS_REGION }})
-#
-#            echo "Current Status: $STATUS"
-#
-#            if [[ "$STATUS" == "Success" ]]; then
-#              echo "Build & Upload Completed ✅"
-#              break
-#            elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
-#              echo "Build & Upload Failed ❌"
-#              exit 1
-#            fi
-#
-#            sleep 5
-#          done
-#          # Fetch the command output once completed
-#          OUTPUT=$(aws ssm get-command-invocation \
-#              --command-id "$COMMAND_ID" \
-#              --instance-id "${{ vars.BUILD_SERVER_EC2_INSTANCE_TAG }}" \
-#              --region ${{ vars.AWS_REGION }} \
-#              --query "StandardOutputContent" --output text)
-#
-#          echo "Command Output:"
-#          echo "$OUTPUT"
+          COMMAND_ID=$(aws ssm send-command \
+            --document-name "AWS-RunShellScript" \
+            --targets '[{"Key":"InstanceIds","Values":["${{ vars.BUILD_SERVER_EC2_INSTANCE_TAG }}"]}]' \
+            --parameters "commands=[
+                'sudo -u ec2-user bash -c \"cd /home/ec2-user/deployer/build_server && source ~/.bashrc && /usr/local/bin/dep deploy --branch=${BRANCH_NAME}\"',
+                'sudo -u ec2-user bash -c \"source ~/.bashrc && cd ${{ vars.BRANCH_PATH }}${BRANCH_NAME_PATH} && tar --zstd -cf ${{vars.BRANCH_ARCHIVES_PATH}}${BRANCH_NAME_PATH}.tar.zst ./.\"',
+                'sudo -u ec2-user bash -c \"export PATH=$PATH:/home/ec2-user/.local/bin:/usr/local/bin && aws s3 cp ${{vars.BRANCH_ARCHIVES_PATH}}${BRANCH_NAME_PATH}.tar.zst ${{ vars.S3_BUILD_PATH }}\"'
+            ]" \
+            --region ${{ vars.AWS_REGION }} \
+            --query "Command.CommandId" --output text)
+
+          echo "Waiting for build and upload to complete..."
+
+          while true; do
+            STATUS=$(aws ssm list-command-invocations \
+              --command-id "$COMMAND_ID" \
+              --details \
+              --query "CommandInvocations[0].Status" \
+              --output text \
+              --region ${{ vars.AWS_REGION }})
+
+            echo "Current Status: $STATUS"
+
+            if [[ "$STATUS" == "Success" ]]; then
+              echo "Build & Upload Completed ✅"
+              break
+            elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
+              echo "Build & Upload Failed ❌"
+              exit 1
+            fi
+
+            sleep 5
+          done
+          # Fetch the command output once completed
+          OUTPUT=$(aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
+              --instance-id "${{ vars.BUILD_SERVER_EC2_INSTANCE_TAG }}" \
+              --region ${{ vars.AWS_REGION }} \
+              --query "StandardOutputContent" --output text)
+
+          echo "Command Output:"
+          echo "$OUTPUT"
 
   deploy_asg:
     runs-on: ubuntu-latest
