commented unit tests

diff --git a/.github/workflows/runUnitTestsAndDeploy.yml b/.github/workflows/runUnitTestsAndDeploy.yml
--- a/.github/workflows/runUnitTestsAndDeploy.yml
+++ b/.github/workflows/runUnitTestsAndDeploy.yml
@@ -17,88 +17,88 @@ on:
       - temp_apcu_poc_aws
 
 jobs:
-  unit_tests:
-    runs-on: ubuntu-latest
-    environment: ${{ inputs.ENVIRONMENT || 'dev' }}
-    env:
-      ENVIRONMENT: ${{ inputs.ENVIRONMENT || 'dev' }}
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
-          aws-region: ${{ vars.AWS_REGION || 'us-east-2' }}
-
-      - name: Fetch EC2 Instance ID
-        id: fetch_instance_id
-        run: |
-          # Fetch the running EC2 instance ID based on the tag and instance state being 'running'
-          INSTANCE_ID=$(aws ec2 describe-instances \
-            --filters "Name=tag:Name,Values=csm-saccess-${{ env.ENVIRONMENT }}-ec2-build" \
-                      "Name=instance-state-name,Values=running" \
-            --query "Reservations[*].Instances[*].InstanceId" \
-            --output text)
-          
-          # Debugging step to see the value of INSTANCE_ID
-          echo "Retrieved INSTANCE_ID = $INSTANCE_ID"
-          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
-
-      - name: Run Unit Tests via SSM
-        run: |
-          BRANCH_NAME=$(echo ${GITHUB_REF##*/})
-          echo "Running Unit Tests on branch: $BRANCH_NAME"
-          
-          COMMAND_ID=$(aws ssm send-command \
-            --document-name "AWS-RunShellScript" \
-            --targets '[{"Key":"InstanceIds","Values":["${{ vars.INSTANCE_ID }}"]}]' \
-            --parameters "commands=['sudo -u ec2-user bash -c \"sudo php /home/ec2-user/unit_test/runUnitTests.php ${BRANCH_NAME}\"']" \
-            --region ${{ vars.AWS_REGION }} \
-            --query "Command.CommandId" --output text)
-          
-          echo "Waiting for test execution to complete..."
-          
-          while true; do
-            STATUS=$(aws ssm list-command-invocations \
-              --command-id "$COMMAND_ID" \
-              --details \
-              --query "CommandInvocations[0].Status" \
-              --output text \
-              --region ${{ vars.AWS_REGION }})
-          
-            echo "Current Status: $STATUS"
-          
-            if [[ "$STATUS" == "Success" ]]; then
-              echo "Unit Tests Passed ✅"
-              break
-            elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
-              echo "Unit Tests Failed ❌"
-              OUTPUT=$(aws ssm get-command-invocation \
-              --command-id "$COMMAND_ID" \
-              --instance-id "${{ vars.INSTANCE_ID }}" \
-              --region ${{ vars.AWS_REGION }} \
-              --query "StandardOutputContent" --output text)
-          
-              echo "Command Output:"
-              echo "$OUTPUT"
-              exit 1
-            fi
-          
-            sleep 5
-          done
-          # Fetch the command output once completed
-          OUTPUT=$(aws ssm get-command-invocation \
-              --command-id "$COMMAND_ID" \
-              --instance-id "${{ vars.INSTANCE_ID }}" \
-              --region ${{ vars.AWS_REGION }} \
-              --query "StandardOutputContent" --output text)
-          
-          echo "Command Output:"
-          echo "$OUTPUT"
+#  unit_tests:
+#    runs-on: ubuntu-latest
+#    environment: ${{ inputs.ENVIRONMENT || 'dev' }}
+#    env:
+#      ENVIRONMENT: ${{ inputs.ENVIRONMENT || 'dev' }}
+#    steps:
+#      - name: Checkout Repository
+#        uses: actions/checkout@v4
+#
+#      - name: Configure AWS Credentials
+#        uses: aws-actions/configure-aws-credentials@v2
+#        with:
+#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
+#          aws-region: ${{ vars.AWS_REGION || 'us-east-2' }}
+#
+#      - name: Fetch EC2 Instance ID
+#        id: fetch_instance_id
+#        run: |
+#          # Fetch the running EC2 instance ID based on the tag and instance state being 'running'
+#          INSTANCE_ID=$(aws ec2 describe-instances \
+#            --filters "Name=tag:Name,Values=csm-saccess-${{ env.ENVIRONMENT }}-ec2-build" \
+#                      "Name=instance-state-name,Values=running" \
+#            --query "Reservations[*].Instances[*].InstanceId" \
+#            --output text)
+#
+#          # Debugging step to see the value of INSTANCE_ID
+#          echo "Retrieved INSTANCE_ID = $INSTANCE_ID"
+#          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
+#
+#      - name: Run Unit Tests via SSM
+#        run: |
+#          BRANCH_NAME=$(echo ${GITHUB_REF##*/})
+#          echo "Running Unit Tests on branch: $BRANCH_NAME"
+#
+#          COMMAND_ID=$(aws ssm send-command \
+#            --document-name "AWS-RunShellScript" \
+#            --targets '[{"Key":"InstanceIds","Values":["${{ vars.INSTANCE_ID }}"]}]' \
+#            --parameters "commands=['sudo -u ec2-user bash -c \"sudo php /home/ec2-user/unit_test/runUnitTests.php ${BRANCH_NAME}\"']" \
+#            --region ${{ vars.AWS_REGION }} \
+#            --query "Command.CommandId" --output text)
+#
+#          echo "Waiting for test execution to complete..."
+#
+#          while true; do
+#            STATUS=$(aws ssm list-command-invocations \
+#              --command-id "$COMMAND_ID" \
+#              --details \
+#              --query "CommandInvocations[0].Status" \
+#              --output text \
+#              --region ${{ vars.AWS_REGION }})
+#
+#            echo "Current Status: $STATUS"
+#
+#            if [[ "$STATUS" == "Success" ]]; then
+#              echo "Unit Tests Passed ✅"
+#              break
+#            elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
+#              echo "Unit Tests Failed ❌"
+#              OUTPUT=$(aws ssm get-command-invocation \
+#              --command-id "$COMMAND_ID" \
+#              --instance-id "${{ vars.INSTANCE_ID }}" \
+#              --region ${{ vars.AWS_REGION }} \
+#              --query "StandardOutputContent" --output text)
+#
+#              echo "Command Output:"
+#              echo "$OUTPUT"
+#              exit 1
+#            fi
+#
+#            sleep 5
+#          done
+#          # Fetch the command output once completed
+#          OUTPUT=$(aws ssm get-command-invocation \
+#              --command-id "$COMMAND_ID" \
+#              --instance-id "${{ vars.INSTANCE_ID }}" \
+#              --region ${{ vars.AWS_REGION }} \
+#              --query "StandardOutputContent" --output text)
+#
+#          echo "Command Output:"
+#          echo "$OUTPUT"
 
 
   build_upload_s3:
@@ -106,7 +106,7 @@ jobs:
     environment: ${{ inputs.ENVIRONMENT || 'dev' }}
     env:
       ENVIRONMENT: ${{ inputs.ENVIRONMENT || 'dev' }}
-    needs: unit_tests
+    #needs: unit_tests
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
