changes

diff --git a/.github/workflows/runUnitTestsAndDeploy.yml b/.github/workflows/runUnitTestsAndDeploy.yml
--- a/.github/workflows/runUnitTestsAndDeploy.yml
+++ b/.github/workflows/runUnitTestsAndDeploy.yml
@@ -128,32 +128,24 @@ jobs:
           echo "Waiting for build and upload to complete..."
 
           while true; do
-          STATUS=$(aws ssm list-command-invocations \
-          --command-id "$COMMAND_ID" \
-          --details \
-          --query "CommandInvocations[0].Status" \
-          --output text \
-          --region ${{ vars.AWS_REGION }})
-          
-          echo "Current Status: $STATUS"
-          
-          # Fetch partial output and print it
-          OUTPUT1=$(aws ssm get-command-invocation \
-            --command-id "$COMMAND_ID" \
-            --instance-id "${{ vars.INSTANCE_ID }}" \
-            --region ${{ vars.AWS_REGION }} \
-            --query "StandardOutputContent" --output text)
-          echo "$OUTPUT1"
-          
-          if [[ "$STATUS" == "Success" ]]; then
-          echo "Build & Upload Completed ✅"
-          break
-          elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
-          echo "Build & Upload Failed ❌"
-          exit 1
-          fi
-          
-          sleep 5
+            STATUS=$(aws ssm list-command-invocations \
+              --command-id "$COMMAND_ID" \
+              --details \
+              --query "CommandInvocations[0].Status" \
+              --output text \
+              --region ${{ vars.AWS_REGION }})
+
+            echo "Current Status: $STATUS"
+
+            if [[ "$STATUS" == "Success" ]]; then
+              echo "Build & Upload Completed ✅"
+              break
+            elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" || "$STATUS" == "Cancelled" ]]; then
+              echo "Build & Upload Failed ❌"
+              exit 1
+            fi
+            
+            sleep 5
           done
           # Fetch the command output once completed
           OUTPUT=$(aws ssm get-command-invocation \
